name: Build and Upload Ethkey Package

on:
  push:
    branches:
      - depelov
  pull_request:
    branches:
      - depelov

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make gcc pkg-config libssl-dev libleveldb-dev clang chrony
        sudo apt-get install -y libleveldb-dev

    - name: Build Package
      run: |
        make all

    - name: Upload Ethkey Package
      uses: actions/upload-artifact@v2
      with:
        name: ethkey-package
        path: build/bin/ethkey
